define(["require", "exports"], function (require, exports) {
    var i18n = {
        root: {
            search: 'Search',
            logOut: 'Log out',
            title: 'Inbox',
            searchPlaceholder: 'Search for anything...',
            email: 'E-mail',
            facebook: 'Facebook',
            twitter: 'Twitter',
            linkedin: 'LinkedIn',
            selectAll: 'select all',
            selectNone: 'select none',
            clickTo: 'Click to',
            or: 'or',
            inbox: 'Inbox',
            drafts: 'Drafts',
            templates: 'Templates',
            outbox: 'Outbox',
            sent: 'Sent',
            trash: 'Trash',
            archive: 'Archive',
            messages: '{NUM, plural, one {1 message} other {# messages}}',
            lastSync: 'Last sync',
            b: 'B',
            kb: 'KB',
            mb: 'MB',
            gb: 'GB',
            tb: 'TB',
            username: 'User Name',
            password: 'Password',
            logMeIn: 'Log me in',
            stayLoggedIn: 'Stay logged in',
            registerAccount: 'Register Account',
            resetPassword: 'Reset Password',
            loginFail: 'Wrong username or password!',
            loginError: 'Oops! Something went wrong. Please try again.',
            to: 'To',
            sendMessage: 'Send Message',
            moveTo: 'Move to',
            messageSent: 'Your message was sent.',
            done: 'Done',
            move: 'Move',
            markAs: 'Mark As',
            read: 'Read',
            unread: 'Unread',
            junk: 'Junk',
            notJunk: 'Not Junk',
            blacklist: 'Blacklist',
            whitelist: 'Whitelist',
            distribute: 'Distribute',
            forward: 'Forward',
            'delete': 'Delete',
            more: 'More',
            reply: 'Reply',
            replyAll: 'Reply All',
            allResults: 'All Results',
            from: 'From',
            subject: 'Subject',
            attachments: 'Attachments',
            message: 'Message',
            allMessages: 'All Messages',
            myMessages: 'My Messages',
            newMessages: 'New Messages',
            source: 'Source',
            sortedBy: 'Sorted by',
            date: 'Date',
            byDate: 'By Date',
            sender: 'Sender',
            bySender: 'By Sender',
            filterBarLabel: '{filter}, sorted by {sort}',
            newMessagesCount: '{NUM, plural, one {1 New Message} other {# New Messages}}',
            congratulations: 'Congratulations!',
            inboxZero: 'You have achieved Inbox Zero',
            noMessages: 'no messages to display',
            searching: 'Searching... This may take a few minutes.',
            draft: 'Draft',
            markAllAsRead: 'Mark all as read',
            toggleReadStatus: 'Mark as {ISREAD, select, true {unread} other {read}}',
            commentMention: '<strong>{NAME}</strong> mentioned you in a comment:',
            sendOptions: 'Send Options',
            priority: 'Priority',
            low: 'Low',
            standard: 'Standard',
            high: 'High',
            draftSaveOnClose: 'Draft Save on Close',
            selectAllCamelCase: 'Select All',
            selectNoneCamelCase: 'Select None',
            minuteUnit: 'm',
            hourUnit: 'h',
            dayUnit: 'd',
            undoQuestion: 'Undo?',
            viewSource: 'View Source'
        }
    };
    return i18n;
});
//# sourceMappingURL=main.js.map